project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Analysis of NYC domestic flights in 2023"
  author:
    - Gaurav Pendharkar (gsp2136)
    - Jason Misquitta (jm5906)
  repo-url: https://github.com/Gaurav0502/us-domestic-flights.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: pulse
    code-fold: true


