---
format: html
engine: knitr
---

```{css}
#| echo: false
p {
  text-align: justify
}
```

# Introduction

Air travel has become a cornerstone of modern transportation, facilitating the movement of millions of passengers and goods daily across the globe. With this surge in air traffic, an immense volume of data is generated, offering valuable insights into various aspects of aviation performance. One critical metric is the on-time performance of flights, which measures how frequently flights adhere to their scheduled departure and arrival times. Flight delays, caused by factors such as weather, air traffic congestion, or operational inefficiencies, have far-reaching consequences, including increased costs for airlines, reduced customer satisfaction, and logistical challenges. Understanding and improving on-time performance is vital for enhancing passenger experience, optimizing airline operations, and ensuring the overall reliability of air travel.

This project delves into the on-time performance of domestic flights serving the New York City (NYC) region in 2023. Through detailed analysis, it explores the reasons behind delays and identifies patterns in their occurrence. Time-series analysis tracks delays over time, uncovering patterns such as peak-hour congestion, seasonal disruptions, or anomalies during specific events. This helps in identifying trends and improving future planning. Meanwhile, geospatial analysis maps delay patterns across locations, highlighting issues like weather-prone regions or congestion at specific airports. By combining these approaches, this project provides a comprehensive understanding of delays, enabling targeted solutions to improve air travel efficiency.

The aim of the project is to answer 9 research questions (RQ) as follows:

1.  How is the on-time performance of the 3 NYC airports (EWR, JFK & LGA) for inbound and outbound flights?

2.  How is the on-time performance of all the airlines having inbound and outbound flights at the 3 airports?

3.  What is the percentage of the different delay ranges for the inbound and outbound flights of the 3 airports?

4.  How is the cascading effect of departure delays on arrival delays?

5.  What are the different factors that affect the arrival delay? How do they impact the arrival delay?

6.  Does the actual hourly air traffic (changes due to delays) differ from the scheduled hourly air traffic for the four quarters?

7.  Are there any monthly or seasonal trends in the delays throughout the year?

8.  Is there any geographical pattern in the delay for inbound and outbound flights for the three airports?

9.  How is the delay distributed on the top-10 busiest routes for the most popular US airlines? 
